CREATE TABLE model (
  provider_id INTEGER NOT NULL,
  id TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (provider_id, id),
  FOREIGN KEY (provider_id) REFERENCES provider (id) ON DELETE CASCADE
);
