[package]
name = "nagai"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "nagai"
path = "src/main.rs"

[dependencies]
crossterm = "0.28"
smol = "2"
dirs = "5"
diesel = { version = "2", features = ["sqlite", "chrono", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = { version = "2", features = ["sqlite"] }
chrono = "0.4"
libsqlite3-sys = { version = "0.31", features = ["bundled"] }
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"
compact_str = "0.10.0"
markdown = "1.0.0"
shellwords = "1.1.0"
dedent = "0.1.1"
async-openai = { version = "0.41", default-features = false, features = ["model", "rustls"] }
futures = "0.3"
